# Copyright (c) ONNX Project Contributors
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "onnx-ir"
SPDX-PackageSupplier = "onnx-technical-discuss@lists.lfaidata.foundation"
SPDX-PackageDownloadLocation = "onnx.ai"

[[annotations]]
path = [
    ".editorconfig",
    ".gitignore",
    "**/*.css",
    "**/*.ipynb",
    "**/*.md",
    "**/*.rst",
    "**/*.toml",
    "**/*.yml",
    "CODEOWNERS",
    "MANIFEST.in",
    "requirements/**/*.txt",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"
